### ISSUE TITLE
Обсуждение синтаксиса

### ISSUE THREAD

**Issue by gorsing** [IxionLang/Ixion#2]
# Обсуждение синтаксиса, просто мои мысли не принимайте близко так как Вы автор и у Вас может быть другой взгляд.
Я за основу взял только
```python
def main(){

    const names = new String[] {
		"Artyom",
		"Alexandr",
		"Danya"
	};

	for(var i = 0; i < names.length; i += 1) {
	    if(i < names.length-1)
		    print(names[i] + ", ");
        else
            print(names[i] + ".");
	}
}
```

Ваш язык напоминает Python с добавлением некоторых черт, похожих на C/C++/Java. Вот что можно отметить в вашем дизайне:

## Особенности текущего дизайна

1. **Синтаксис функции**:
    - У вас используется синтаксис `def main(){}`, который напоминает C++ или Java. 
    - Однако `def` как ключевое слово чаще ассоциируется с Python.

2. **Объявление массивов**:
    - Использование `new String[]` выглядит как комбинация Java (с `new` и указанием типа массива) и C# (с явным типом).

3. **Цикл `for`**:
    - Указание `for(var i = 0; i < names.length; i += 1)` — это стандартный подход из C/C++, но с использованием `var`, который популярен в современных языках, таких как JavaScript и C#.

4. **Функция `print`**:
    - Лучше чтобы `print` стал ключевой частью вашего языка, имеет смысл сделать его встроенной функцией, похожей на Python или JavaScript. Это приблизит его к python3

5. **Особенности вашего подхода**:
    - В языке нет явной привязки к Python-стилю форматирования строк или встроенным функциям работы с коллекциями (как в `join`).
    - Управляющие конструкции выглядят строго типизированными, но с элементами динамической типизации через `var`.

---

## Возможные улучшения/доработки

1. **Массивы и типизация**:
    Если ваш язык должен быть современным и гибким, можно сократить код с использованием более лаконичного синтаксиса:
    ```python
    const names = ["Artyom", "Alexandr", "Danya"];
    ```

2. **Циклы и итерации**:
    Предоставьте возможность использовать более удобный итератор, например:
    ```python
    for name in names {
        print(name);
    }
    ```

3. **Форматирование строк**:
    Если вдохновляет Python, добавьте поддержку форматирования. Это приблизит его к Python, например:
    ```python
    print(f"{name}, ");
    ```

4. **Особенности блоков**:
    Введённые вами фигурные скобки `{}` могут быть заменены на отступы автоматически или полуавтоматически, если хотите сохранить дух Python, или оставить их для гибкости, как в C/C++/Java. Например, если взять простую функцию на Python, она может автоматически конвертироваться в ваш язык. Вот пример:
    ```python
    # Python
    def greet():
        print("Hello, world!")
    ```
    Автоматически преобразуется в:
    ```
    def greet() {
        print("Hello, world!");
    }
    ```

5. **Примеры вашего языка**:
    Вот как может выглядеть пример на улучшённом языке:
    ```python
    def main() {
        const names = ["Artyom", "Alexandr", "Danya"];
        for name in names[:-1] {
            print(f"{name}, ");
        }
        print(names[-1] + ".");
    }
    ```

6. **Совместимость с Python**:
    Если вы хотите, чтобы язык был совместим с Python, можно разрешить смешивать стили.

---

**Comment by Animemchik** [comment]
Чел я тоже умею ChatGPT юзать
И ты на столько ущербный что даже не сказал ChatGPT что этот язык компилируется в байткод JVM

**Comment by gorsing** [comment]
А если вы автор я вам сочуствую ... язык это не только автор а и комюнити...

**Comment by ArtyomKingmang** [comment]
Так а при чем тут он и этот язык?

**Comment by gorsing** [comment]
@ArtyomKingmang Добрый день. Мне понравилась идея и ваш труд...  Я поделился свими мыслями которые подредактировал с ChatGPT. Я не буду это отрицать... 
Буду рад конструкциву.

**Comment by Monsler** [comment]
имба чатгпт. А о том, обречён этот язык или нет, судить ты не можешь

**Comment by ArtyomKingmang** [comment]
> # Обсуждение синтаксиса, просто мои мысли не принимайте близко так как Вы автор и у Вас может быть другой взгляд.
> Я за основу взял только
> ```python
> def main(){
> 
>     const names = new String[] {
> 		"Artyom",
> 		"Alexandr",
> 		"Danya"
> 	};
> 
> 	for(var i = 0; i < names.length; i += 1) {
> 	    if(i < names.length-1)
> 		    print(names[i] + ", ");
>         else
>             print(names[i] + ".");
> 	}
> }
> ```
> 
> Ваш язык напоминает Python с добавлением некоторых черт, похожих на C/C++/Java. Вот что можно отметить в вашем дизайне:
> 
> ## Особенности текущего дизайна
> 
> 1. **Синтаксис функции**:
>     - У вас используется синтаксис `def main(){}`, который напоминает C++ или Java. 
>     - Однако `def` как ключевое слово чаще ассоциируется с Python.
> 
> 2. **Объявление массивов**:
>     - Использование `new String[]` выглядит как комбинация Java (с `new` и указанием типа массива) и C# (с явным типом).
> 
> 3. **Цикл `for`**:
>     - Указание `for(var i = 0; i < names.length; i += 1)` — это стандартный подход из C/C++, но с использованием `var`, который популярен в современных языках, таких как JavaScript и C#.
> 
> 4. **Функция `print`**:
>     - Лучше чтобы `print` стал ключевой частью вашего языка, имеет смысл сделать его встроенной функцией, похожей на Python или JavaScript. Это приблизит его к python3
> 
> 5. **Особенности вашего подхода**:
>     - В языке нет явной привязки к Python-стилю форматирования строк или встроенным функциям работы с коллекциями (как в `join`).
>     - Управляющие конструкции выглядят строго типизированными, но с элементами динамической типизации через `var`.
> 
> ---
> 
> ## Возможные улучшения/доработки
> 
> 1. **Массивы и типизация**:
>     Если ваш язык должен быть современным и гибким, можно сократить код с использованием более лаконичного синтаксиса:
>     ```python
>     const names = ["Artyom", "Alexandr", "Danya"];
>     ```
> 
> 2. **Циклы и итерации**:
>     Предоставьте возможность использовать более удобный итератор, например:
>     ```python
>     for name in names {
>         print(name);
>     }
>     ```
> 
> 3. **Форматирование строк**:
>     Если вдохновляет Python, добавьте поддержку форматирования. Это приблизит его к Python, например:
>     ```python
>     print(f"{name}, ");
>     ```
> 
> 4. **Особенности блоков**:
>     Введённые вами фигурные скобки `{}` могут быть заменены на отступы автоматически или полуавтоматически, если хотите сохранить дух Python, или оставить их для гибкости, как в C/C++/Java. Например, если взять простую функцию на Python, она может автоматически конвертироваться в ваш язык. Вот пример:
>     ```python
>     # Python
>     def greet():
>         print("Hello, world!")
>     ```
>     Автоматически преобразуется в:
>     ```
>     def greet() {
>         print("Hello, world!");
>     }
>     ```
> 
> 5. **Примеры вашего языка**:
>     Вот как может выглядеть пример на улучшённом языке:
>     ```python
>     def main() {
>         const names = ["Artyom", "Alexandr", "Danya"];
>         for name in names[:-1] {
>             print(f"{name}, ");
>         }
>         print(names[-1] + ".");
>     }
>     ```
> 
> 6. **Совместимость с Python**:
>     Если вы хотите, чтобы язык был совместим с Python, можно разрешить смешивать стили.
> 
> ---
> 

Что касается вашего issue: я не понял при чем тут совместимость с питоном, поэтому лучше этот момент поясните. Все эти конструкции, кроме f-строк будут введены в будущем. Интерполяция строк в ixion будет реализована по-другому

**Comment by gorsing** [comment]
Если говорить глобально то для меня не хватает roadmap -a. Да бы когда появится свободное время возможно присоединится ...  
Совместимость с питоном, это как я вас понял(ошибочно). Но из этого обсуждения мне уже стало более понятнее...
 f-строки можно скипнуть... Вы автор и вы проектируете ...

**Comment by zethange** [comment]
ладно, это было забавно

**Comment by Animemchik** [comment]
> Ущербный @Animemchik Ха, предложи лучше... Или ты класический троль? А

Б
Чел ты даже не прочитал нормально README
Если бы прочитал, то сразу бы понял
Сразу под заголовком "Multi-paradigm compiled programming language for the jvm platform."
Если ты прочитал, то значит не понимаешь, что ты не сможешь сделать нормальную работу с пайтоном через байткод JVM
